compressionLevel: 0

enableGlobalCache: false

enableHardenedMode: false # Disables hardened mode in CI for faster installs, we set immutable in CI instead

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs
